account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from account import views

app_name = "account"

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('edit/', views.edit, name='edit'),
]

home_accounting/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from rest_framework.routers import SimpleRouter

from rest.views import TransferViewSet

router = SimpleRouter()
router.register(r'transfer', TransferViewSet)

urlpatterns = [
    path('', include('transfers.urls')),
    path('account/', include(('account.urls'), namespace='account')),
    path('admin/', admin.site.urls),
]

urlpatterns += router.urls

urlpatterns += staticfiles_urlpatterns()

transfers/urls.py
from django.contrib import admin
from django.urls import path, include

from transfers import views

urlpatterns = [
    path('', views.TransfersView.as_view(), name='transfers-list'),
    path('transfer/delete/<int:pk>/', views.TransferDeleteView.as_view(), name='transfer-delete'),
    path('transfer/update/<int:pk>/', views.TransferUpdateView.as_view(), name='transfer-update'),
    path('transfer/detail/<int:pk>/', views.TransferDetailView.as_view(), name='transfer-detail'),
]

transfers/models.py
from django.contrib.auth.models import User
from django.db import models


class CategoryTransfer(models.Model):
    """ Модель типа категории проводки """
    DEFAULT_ID = 1
    name = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.name}'


class Transfer(models.Model):
    """ Модель проводки """
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, verbose_name='Пользователь')
    data = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    sum = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Сумма")
    category = models.ForeignKey(CategoryTransfer, on_delete=models.SET_DEFAULT, default=CategoryTransfer.DEFAULT_ID, verbose_name='Категория')
    comment = models.CharField(max_length=200, blank=True, verbose_name='Комментарий')
    TYPE_SELECTION = (
        ('+', 'Приход'),
        ('-', 'Расход')
    )
    type_transfer = models.CharField(max_length=1, choices=TYPE_SELECTION, blank=True, default=TYPE_SELECTION[1], verbose_name='Тип движения')

    def __str__(self):
        return f"{self.data.strftime('%m.%d.%y %H:%M:%S')}: {self.type_transfer} {self.sum} руб."

transfers/views.py
import datetime

import pytz
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db.models import Sum
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from account.models import Profile
from home_accounting import settings
from transfers.models import Transfer


class TestUserOwnerOfTransfer(UserPassesTestMixin):
    """ Миксин, проверяющий совпадение владельца записи с текущим пользователем """
    def test_func(self):
        self.object = self.get_object()
        return self.request.user == self.object.user


@method_decorator(login_required, name='dispatch')
class TransfersView(CreateView):
    """ Создание модели, с расширением в get_context_data вывода списка всех транзакций """
    model = Transfer
    template_name = 'transfers/index.html'
    fields = ('type_transfer', 'sum', 'category', 'comment',)
    success_url = reverse_lazy('transfers-list')

    def get_context_data(self, **kwargs):
        kwargs['object_list'] = self.request.user.transfer_set.all().order_by('-data')
        # time_zone = pytz.timezone(settings.TIME_ZONE)
        time_zone = pytz.timezone('UTC')
        positive_sum = Transfer.objects.filter(user=self.request.user,
                                               type_transfer='+',
                                               data__range=(datetime.datetime.now(time_zone).replace(day=1, hour=0,minute=0,second=0,microsecond=0),
                                                            datetime.datetime.now(time_zone))).aggregate(Sum('sum'))
        negative_sum = Transfer.objects.filter(user=self.request.user,
                                               type_transfer='-',
                                               data__range=(datetime.datetime.now(time_zone).replace(day=1),
                                                            datetime.datetime.now(time_zone))).aggregate(Sum('sum'))
        if positive_sum['sum__sum'] is None:
            positive_sum['sum__sum'] = 0
        if negative_sum['sum__sum'] is None:
            negative_sum['sum__sum'] = 0
        total_sum = positive_sum['sum__sum'] - negative_sum['sum__sum']
        kwargs['total_sum'] = "{:.2f}".format(total_sum)
        kwargs['over_budget'] = Profile.objects.get(user=self.request.user).budget + total_sum
        return super(TransfersView, self).get_context_data(**kwargs)

    def form_valid(self, form):
        """ Автоматически подставляет пользователя в запись из запроса """
        form.instance.user = self.request.user
        return super(TransfersView, self).form_valid(form)


@method_decorator(login_required, name='dispatch')
class TransferDetailView(TestUserOwnerOfTransfer, DetailView):
    """ Просмотр записи """
    model = Transfer
    template_name = 'transfers/detail.html'
    context_object_name = 'transfer'


@method_decorator(login_required, name='dispatch')
class TransferUpdateView(TestUserOwnerOfTransfer, UpdateView):
    """ Редактирование записи """
    model = Transfer
    template_name = 'transfers/update.html'
    context_object_name = 'transfer'
    fields = ('type_transfer', 'sum', 'category', 'comment',)

    def get_success_url(self):
        """ путь для перехода при успешном выполнении """
        return reverse_lazy('transfer-detail', kwargs={'pk': self.object.id})


@method_decorator(login_required, name='dispatch')
class TransferDeleteView(TestUserOwnerOfTransfer, DeleteView):
    """ Удаление записи """
    model = Transfer
    template_name = 'transfers/delete.html'
    success_url = reverse_lazy('transfers-list')

templates/transfers/delete.html
{% extends "__base.html" %}
{% block container %}
    {% if request.user == transfer.user %}
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Удалить запись {{object}}</h5>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="alert alert-warning" role="alert">
                        Вы уверены что хотите удалить запись: <strong>{{ object }}</strong>?
                    </div>
                    <button type="submit" class="btn btn-danger">Удалить</button>
                </form>
            </div>
        </div>
    {% else %}
        <h4 class="card-title">Запись отсутствует или удалена</h4>
    {% endif %}
{% endblock %}

templates/transfers/detail.html
{% extends "__base.html" %}
{% block container %}
    {% if request.user == transfer.user %}
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Подробности об операции от {{transfer.data}}</h5>
            </div>
            <div class="card-body">
                <dl class="row">
{#                    <dt class="col-sm-3">Информация об операции:</dt>#}
                    <dt class="col-sm-3">Дата:</dt>
                    <dd class="col-sm-9">{{ transfer.data }}</dd>
                    <dt class="col-sm-3">Тип:</dt>
                    <dd class="col-sm-9">{{ transfer.category.name }}</dd>
                    <dt class="col-sm-3">Сумма:</dt>
                    <dd class="col-sm-9">{{ transfer.sum }}</dd>
                    <dt class="col-sm-3">Комментарий:</dt>
                    <dd class="col-sm-9">{{ transfer.comment }}</dd>
                </dl>

            </div>
        </div>
    {% else %}
        <h4 class="card-title">Запись отсутствует или удалена</h4>
    {% endif %}
{% endblock %}

templates/transfers/index.html
{% extends "__base.html" %}

{% block container %}
    <div class="card">
        <div class="card-header">
            <h5 class="card-title">Добавить запись</h5>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <label for="id_sum">Сумма:</label>
            <div class="col-md-6">
                <div class="input-group mb-3">
                    <input type="number" class="form-control" name="sum" step="0.01" required="" id="id_sum">
                    <select class="form-control" name="type_transfer" id="id_type_transfer">
                        <option value="-" selected>Расход</option>
                        <option value="+">Приход</option>
                    </select>
                </div>
            </div>
                <label for="id_category">Категория:</label>
                <div class="col-md-6">
                    <p>
                        <select class="form-control" name="category" id="id_category">
                            {% for category in category_list %}
                                <option value="{{ category.id }}">{{ category.name }}</option>
                            {% endfor %}
                        </select>
                    </p>
                </div>

                <label for="id_comment">Комментарий:</label>
                <div class="col-md-6">
                    <p>
                        <textarea class="form-control" name="comment" maxlength="200" id="id_comment"></textarea>
                    </p>
                </div>
                <button type="submit" class="btn btn-success">Записать</button>
            </form>
        </div>
    </div>
    {%  if object_list.count == 0 %}
        <p>
        <h2><span class="badge badge-secondary">У Вас еще нет записанных операций</span></h2>
        </p>
    {% else %}
        <p>
        <h2>История операций на {% now "d.m.Y" %}.
            {% if over_budget < 0 %}
                Баланс на текущий месяц: <span class="badge badge-danger">{{ total_sum }} руб.</span>
            {% else %}
                Баланс на текущий месяц: <span class="badge badge-success">{{ total_sum }} руб.</span>
            {% endif %}
        </h2>
        </p>
        <table class="table">
            <tr>
                <thead class="thead-light">
                <tr>
                    <th scope="col">Дата</th>
                    <th scope="col">Операция</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                {% for transfer in object_list %}
                    <tr>
                        <td><a href="{% url 'transfer-detail' transfer.pk %}">{{ transfer.data|date:"d.m.Y H:i:s" }}</a></td>
                        <td><a href="{% url 'transfer-detail' transfer.pk %}">{{ transfer.type_transfer }} {{transfer.sum}}</a></td>
                        <td><a href="{% url 'transfer-update' transfer.pk %}" class="btn btn-info" role="button">Подробнее</a></td>
                        <td><a href="{% url 'transfer-delete' transfer.pk %}" class="btn btn-danger" role="button">Удалить</a></td>
                    </tr>
                {% endfor %}
                </tbody>
        </table>
    {% endif %}
{% endblock %}

templates/transfers/update.html
{% extends "__base.html" %}
{% block container %}
    {% if request.user == transfer.user %}
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Изменить запись #{{transfer}}</h5>
            </div>
            <div class="card-body">

                <form method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-success">Изменить</button>
                </form>
            </div>
        </div>
    {% else %}
        <h4 class="card-title">Запись отсутствует или удалена</h4>
    {% endif %}
{% endblock %}