account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from account import views

app_name = "account"

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('edit/', views.edit, name='edit'),
]

home_accounting/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from rest_framework.routers import SimpleRouter

from rest.views import TransferViewSet

router = SimpleRouter()
router.register(r'transfer', TransferViewSet)

urlpatterns = [
    path('', include('transfers.urls')),
    path('account/', include(('account.urls'), namespace='account')),
    path('admin/', admin.site.urls),
]

urlpatterns += router.urls

urlpatterns += staticfiles_urlpatterns()

templates/__base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block meta_tags %}{% endblock %}
    <title>{% block title %}Личная бухгалтерия{% endblock %}</title>

    {% block css %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% endblock %}

    {% block custom_css %}
    {% endblock %}
</head>
<body>

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'transfers-list' %}">Главная</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

{#            <div class="collapse navbar-collapse" id="navbarSupportedContent">#}
{#                <ul class="navbar-nav mr-auto">#}
{#                    <li class="nav-item active">#}
{#                        <a class="nav-link" href="#">Home</a>#}
{#                    </li>#}
{#                </ul>#}
{#                <ul class="header-links pull-right">#}
{#                    <li class="nav-item active">#}
            <div class="header-links pull-right">
                        {% if not request.user.is_authenticated %}
                            <a class="btn btn-success" href="{% url 'account:login' %}" role="button">Вход</a>
                            <a class="btn btn-success" href="{% url 'account:register' %}" role="button">Регистрация</a>
{#                            <a href="{% url 'account:login' %}"><i class="fa fa-user-o"></i>Вход</a>#}
{#                            <a href="{% url 'account:register' %}"><i></i>Регистрация</a>#}
                        {% else %}
                            <a class="btn btn-success" href="{% url 'account:edit' %}" role="button">{{ request.user.username }}</a>
                            <a class="btn btn-success" href="{% url 'account:logout' %}" role="button">Выход</a>
{#                            <a href="{% url 'account:login' %}"><i class="fa fa-user-o"></i>{{ request.user }}</a>#}
{#                            <a href="{% url 'account:logout' %}"><i></i>Выход</a>#}
                        {% endif %}
            </div>
{#                    </li>#}
{#                </ul>#}
{#            </div>#}
        </div>
    </nav>
{% endblock %}

<div class="container mt-4">
{#<div class="container-fluid">#}
    {% block container %}
    {% endblock %}
</div>

{% block js %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock %}

{% block custom_js %}
{% endblock %}
</body>
</html>

templates/_pagination.html
<nav aria-label="navigation">
    <ul class="pagination justify-content-end mb-0">
{% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <i class="fas fa-angle-left"></i>
            <span class="sr-only">Previous</span>
        </a>
    </li>
{% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">
            <i class="fas fa-angle-left"></i>
            <span class="sr-only">Previous</span>
        </a>
    </li>
{% endif %}

{% for i in page_obj.paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="page-item active">
        <a class="page-link" href="?page={{ i }}">{{ page_obj.number }}</a>
      </li>
    {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
    <li class="page-item">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
      </li>
    {% endif %}
{% endfor %}

{% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
    <li><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
{% endif %}

{% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          <i class="fas fa-angle-right"></i>
          <span class="sr-only">Next</span>
        </a>
      </li>
{% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">
            <i class="fas fa-angle-right"></i>
            <span class="sr-only">Next</span>
        </a>
    </li>
{% endif %}
</ul>
</nav>